# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_remove_page_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['page_order']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question_order']},
        ),
        migrations.AddField(
            model_name='page',
            name='page_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='question_order',
            field=models.IntegerField(default=0),
        ),
    ]
