# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_auto_20170711_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_score',
            field=models.IntegerField(default=0),
        ),
    ]
